import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { query, initDb } from './db.js';
import { hashPassword, comparePassword, signToken, requireAuth, requireAdmin, ensureAdmin } from './auth.js';
import { uploadSignature } from './cloudinary.js';
dotenv.config();

const app=express();
const PORT=process.env.PORT||10000;
const allowed=(process.env.CORS_ORIGIN||'*').split(',').map(x=>x.trim());
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:(origin,cb)=>{if(!origin||allowed.includes('*')||allowed.includes(origin)) return cb(null,true); cb(new Error('CORS blocked'));}}));
app.use(express.json({limit:'1mb'}));
app.use(morgan('combined'));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:100,standardHeaders:true,legacyHeaders:false}));
const __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use('/admin',express.static(path.join(__dirname,'../public/admin')));
app.get('/',(_,res)=>res.json({name:'Jagdamba Optical API',status:'ok',admin:'/admin'}));
app.get('/health',async(_,res)=>{try{await query('SELECT 1');res.json({status:'ok',database:'connected'})}catch(e){res.status(503).json({status:'error',database:'disconnected'})}});

app.post('/api/auth/admin/login',async(req,res)=>{try{const {email,password}=req.body;if(!email||!password)return res.status(400).json({error:'Email and password are required'});const r=await query('SELECT * FROM admins WHERE lower(email)=lower($1)',[email]);if(!r.rowCount||!(await comparePassword(password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});const a=r.rows[0];res.json({token:signToken({id:a.id,role:'admin',email:a.email,name:a.name}),user:{id:a.id,name:a.name,email:a.email,role:'admin'}})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});const existing=await query('SELECT id FROM customers WHERE lower(email)=lower($1)',[email]);if(existing.rowCount)return res.status(409).json({error:'Email already registered'});const r=await query('INSERT INTO customers(name,email,phone,password_hash) VALUES($1,$2,$3,$4) RETURNING id,name,email,phone',[name,email.toLowerCase(),phone||null,await hashPassword(password)]);const c=r.rows[0];res.status(201).json({token:signToken({id:c.id,role:'customer',email:c.email,name:c.name}),user:{...c,role:'customer'}})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const r=await query('SELECT * FROM customers WHERE lower(email)=lower($1)',[email]);if(!r.rowCount||!r.rows[0].password_hash||!(await comparePassword(password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});const c=r.rows[0];res.json({token:signToken({id:c.id,role:'customer',email:c.email,name:c.name}),user:{id:c.id,name:c.name,email:c.email,phone:c.phone,role:'customer'}})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/categories',async(req,res)=>{try{const r=await query('SELECT * FROM categories WHERE active=true ORDER BY name');res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/products',async(req,res)=>{try{const {search,category,type,featured,limit='100',offset='0'}=req.query;const where=['p.is_active=true'];const vals=[];if(search){vals.push(`%${search}%`);where.push(`(p.name ILIKE $${vals.length} OR p.brand ILIKE $${vals.length} OR p.sku ILIKE $${vals.length})`)}if(category){vals.push(category);where.push(`c.slug=$${vals.length}`)}if(type){vals.push(type);where.push(`p.product_type=$${vals.length}`)}if(featured==='true')where.push('p.is_featured=true');vals.push(Math.min(Number(limit)||100,200),Math.max(Number(offset)||0,0));const r=await query(`SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE ${where.join(' AND ')} ORDER BY p.created_at DESC LIMIT $${vals.length-1} OFFSET $${vals.length}`,vals);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/products/:id',async(req,res)=>{try{const r=await query('SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=$1 AND p.is_active=true',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/orders',async(req,res)=>{const client=await (await import('./db.js')).pool.connect();try{const {customerId,customerName,customerEmail,customerPhone,shippingAddress,items,paymentMethod='cod',notes=''}=req.body;if(!customerName||!customerPhone||!shippingAddress||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Customer details, address and items are required'});await client.query('BEGIN');let subtotal=0;const clean=[];for(const item of items){const r=await client.query('SELECT id,sku,name,price,stock,is_active FROM products WHERE id=$1 FOR UPDATE',[item.productId]);if(!r.rowCount||!r.rows[0].is_active)throw new Error(`Product ${item.productId} is unavailable`);const p=r.rows[0];const qty=Math.max(1,Number(item.quantity)||1);if(p.stock<qty)throw new Error(`${p.name} has only ${p.stock} item(s) in stock`);const line=Number(p.price)*qty;subtotal+=line;clean.push({...p,quantity:qty,line});}const shipping=subtotal>=999?0:80;const total=subtotal+shipping;const orderNo=`JO-${Date.now().toString().slice(-8)}-${Math.floor(100+Math.random()*900)}`;const order=await client.query(`INSERT INTO orders(order_number,customer_id,customer_name,customer_email,customer_phone,shipping_address,subtotal,shipping_fee,total,payment_method,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[orderNo,customerId||null,customerName,customerEmail||null,customerPhone,JSON.stringify(shippingAddress),subtotal,shipping,total,paymentMethod,notes]);for(const p of clean){await client.query('INSERT INTO order_items(order_id,product_id,sku,product_name,quantity,unit_price,line_total) VALUES($1,$2,$3,$4,$5,$6,$7)',[order.rows[0].id,p.id,p.sku,p.name,p.quantity,p.price,p.line]);await client.query('UPDATE products SET stock=stock-$1,updated_at=NOW() WHERE id=$2',[p.quantity,p.id]);}await client.query('COMMIT');res.status(201).json({message:'Order created',order:order.rows[0]});}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}fin
ally{client.release()}});
app.post('/api/inquiries',async(req,res)=>{try{const {name,email,phone,subject,message}=req.body;if(!name||!message)return res.status(400).json({error:'Name and message are required'});const r=await query('INSERT INTO inquiries(name,email,phone,subject,message) VALUES($1,$2,$3,$4,$5) RETURNING *',[name,email||null,phone||null,subject||null,message]);res.status(201).json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/admin/dashboard',requireAuth,requireAdmin,async(_,res)=>{try{const [sales,orders,customers,products,pending,inquiries]=await Promise.all([query("SELECT COALESCE(SUM(total),0) total FROM orders WHERE payment_status='paid' OR payment_method='cod'"),query('SELECT COUNT(*) FROM orders'),query('SELECT COUNT(*) FROM customers'),query('SELECT COUNT(*) FROM products WHERE is_active=true'),query("SELECT COUNT(*) FROM orders WHERE status IN ('pending','processing')"),query("SELECT COUNT(*) FROM inquiries WHERE status='new'")]);res.json({sales:Number(sales.rows[0].total),orders:Number(orders.rows[0].count),customers:Number(customers.rows[0].count),products:Number(products.rows[0].count),pendingOrders:Number(pending.rows[0].count),newInquiries:Number(inquiries.rows[0].count)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/products',requireAuth,requireAdmin,async(_,res)=>{try{const r=await query('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.created_at DESC');res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/products',requireAuth,requireAdmin,async(req,res)=>{try{const p=req.body;const r=await query(`INSERT INTO products(category_id,sku,brand,name,description,product_type,price,compare_price,stock,image_url,images,color,size,gender,is_featured,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[p.categoryId||null,p.sku,p.brand,p.name,p.description||null,p.productType||'eyeglasses',p.price,p.comparePrice||null,p.stock||0,p.imageUrl||null,JSON.stringify(p.images||[]),p.color||null,p.size||null,p.gender||null,!!p.isFeatured,p.isActive!==false]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/admin/products/:id',requireAuth,requireAdmin,async(req,res)=>{try{const p=req.body;const r=await query(`UPDATE products SET category_id=$1,sku=$2,brand=$3,name=$4,description=$5,product_type=$6,price=$7,compare_price=$8,stock=$9,image_url=$10,images=$11,color=$12,size=$13,gender=$14,is_featured=$15,is_active=$16,updated_at=NOW() WHERE id=$17 RETURNING *`,[p.categoryId||null,p.sku,p.brand,p.name,p.description||null,p.productType||'eyeglasses',p.price,p.comparePrice||null,p.stock||0,p.imageUrl||null,JSON.stringify(p.images||[]),p.color||null,p.size||null,p.gender||null,!!p.isFeatured,p.isActive!==false,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/admin/products/:id',requireAuth,requireAdmin,async(req,res)=>{try{await query('UPDATE products SET is_active=false,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({message:'Product disabled'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/orders',requireAuth,requireAdmin,async(req,res)=>{try{const r=await query(`SELECT o.*,COALESCE(json_agg(json_build_object('id',oi.id,'productId',oi.product_id,'name',oi.product_name,'quantity',oi.quantity,'unitPrice',oi.unit_price,'lineTotal',oi.line_total)) FILTER(WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.created_at DESC`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/orders/:id',requireAuth,requireAdmin,async(req,res)=>{try{const allowedStatus=['pending','processing','shipped','delivered','cancelled'];const allowedPayment=['pending','paid','failed','refunded'];const {status,paymentStatus}=req.body;if(status&&!allowedStatus.includes(status))return res.status(400).json({error:'Invalid order status'});if(paymentStatus&&!allowedPayment.includes(paymentStatus))return res.status(400).json({error:'Invalid payment status'});const r=await query('UPDATE orders SET status=COALESCE($1,status),payment_status=COALESCE($2,payment_status),updated_at=NOW() WHERE id=$3 RETURNING *',[status||null,paymentStatus||null,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Order not found'});res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/customers',requireAuth,requireAdmin,async(_,res)=>{try{const r=await query(`SELECT c.id,c.name,c.email,c.phone,c.created_at,COUNT(o.id)::int order_count,COALESCE(SUM(o.total),0) total_spent FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/inquiries',requireAuth,requireAdmin,async(_,res)=>{try{const r=await query('SELECT * FROM inquiries ORDER BY created_at DESC');res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/inquiries/:id',requireAuth,requireAdmin,async(req,res)=>{try{const r=await query('UPDATE inquiries SET status=$1 WHERE id=$2 RETURNING *',[req.body.status||'read',req.params.id]);res.json(r.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/categories',requireAuth,requireAdmin,async(_,res)=>{try{const r=await query('SELECT * FROM categories ORDER BY name');res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/categories',requireAuth,requireAdmin,async(req,res)=>{try{const {name,slug,description,imageUrl}=req.body;const r=await query('INSERT INTO categories(name,slug,description,image_url) VALUES($1,$2,$3,$4) RETURNING *',[name,slug,description||null,imageUrl||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/upload-signature',requireAuth,requireAdmin,(_,res)=>{const data=uploadSignature();if(!data)return res.status(503).json({error:'Cloudinary is not configured. Add Cloudinary environment variables first.'});res.json(data)});

const seedCategories=[['Eyeglasses','eyeglasses'],['Sunglasses','sunglasses'],['Kids','kids'],['Computer Glasses','computer-glasses'],['Lenses','lenses']];
const seedProducts=[['JOHN-JJ-001','JOHN JACOBS','Tortoise Round Eyeglasses',1299,2199,'eyeglasses'],['VC-BR-002','VINCENT CHASE','Black Rectangle Eyeglasses',999,1799,'eyeglasses'],['AIR-BL-003','AIR FLEX','Blue Square Eyeglasses',1199,1999,'eyeglasses'],['ID-BR-004','IDEE','Brown Wayfarer Eyeglasses',1099,1899,'eyeglasses'],['FS-BR-005','FASTRACK','Black & Red Eyeglasses',949,1599,'eyeglasses'],['RB-AV-006','RAY-BAN','Aviator Sunglasses',2699,4499,'sunglasses'],['VC-PL-007','VINCENT CHASE','Polarized Sunglasses',1599,2799,'sunglasses'],['OK-SP-008','OAKLEY','Sports Sunglasses',3499,5999,'sunglasses']];
async function seed(){for(const [name,slug] of seedCategories)await query('INSERT INTO categories(name,slug) VALUES($1,$2) ON CONFLICT(slug) DO NOTHING',[name,slug]);for(const [sku,brand,name,price,compare,type] of seedProducts){const c=await query('SELECT id FROM categories WHERE slug=$1',[type]);await query(`INSERT INTO products(category_id,sku,brand,name,price,compare_price,stock,product_type,image_url) VALUES($1,$2,$3,$4,$5,$6,25,$7,$8) ON CONFLICT(sku) DO NOTHING`,[c.rows[0]?.id,sku,brand,name,price,compare,type,'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=800&q=85']);}}

(async()=>{try{await initDb();await ensureAdmin();await seed();app.listen(PORT,()=>console.log(`Jagdamba Optical API running on port ${PORT}`));}catch(e){console.error(e);process.exit(1)}})();